//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Test", "FK_CorrectOptionTable_QuestionTable", "QuestionTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Test.QuestionTable), "CorrectOptionTable", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Test.CorrectOptionTable), true)]
[assembly: EdmRelationshipAttribute("Test", "FK_QuestionTable_ExamTable", "ExamTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Test.ExamTable), "QuestionTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Test.QuestionTable), true)]
[assembly: EdmRelationshipAttribute("Test", "FK_ResultTable_ExamTable", "ExamTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Test.ExamTable), "ResultTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Test.ResultTable), true)]
[assembly: EdmRelationshipAttribute("Test", "FK_OptionTable_QuestionTable", "QuestionTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Test.QuestionTable), "OptionTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Test.OptionTable), true)]
[assembly: EdmRelationshipAttribute("Test", "FK_ResultTable_UserTable", "UserTable", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Test.UserTable), "ResultTable", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Test.ResultTable), true)]

#endregion

namespace Test
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TestEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TestEntities object using the connection string found in the 'TestEntities' section of the application configuration file.
        /// </summary>
        public TestEntities() : base("name=TestEntities", "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEntities object.
        /// </summary>
        public TestEntities(string connectionString) : base(connectionString, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TestEntities object.
        /// </summary>
        public TestEntities(EntityConnection connection) : base(connection, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CorrectOptionTable> CorrectOptionTables
        {
            get
            {
                if ((_CorrectOptionTables == null))
                {
                    _CorrectOptionTables = base.CreateObjectSet<CorrectOptionTable>("CorrectOptionTables");
                }
                return _CorrectOptionTables;
            }
        }
        private ObjectSet<CorrectOptionTable> _CorrectOptionTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExamTable> ExamTables
        {
            get
            {
                if ((_ExamTables == null))
                {
                    _ExamTables = base.CreateObjectSet<ExamTable>("ExamTables");
                }
                return _ExamTables;
            }
        }
        private ObjectSet<ExamTable> _ExamTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OptionTable> OptionTables
        {
            get
            {
                if ((_OptionTables == null))
                {
                    _OptionTables = base.CreateObjectSet<OptionTable>("OptionTables");
                }
                return _OptionTables;
            }
        }
        private ObjectSet<OptionTable> _OptionTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuestionTable> QuestionTables
        {
            get
            {
                if ((_QuestionTables == null))
                {
                    _QuestionTables = base.CreateObjectSet<QuestionTable>("QuestionTables");
                }
                return _QuestionTables;
            }
        }
        private ObjectSet<QuestionTable> _QuestionTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ResultTable> ResultTables
        {
            get
            {
                if ((_ResultTables == null))
                {
                    _ResultTables = base.CreateObjectSet<ResultTable>("ResultTables");
                }
                return _ResultTables;
            }
        }
        private ObjectSet<ResultTable> _ResultTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserTable> UserTables
        {
            get
            {
                if ((_UserTables == null))
                {
                    _UserTables = base.CreateObjectSet<UserTable>("UserTables");
                }
                return _UserTables;
            }
        }
        private ObjectSet<UserTable> _UserTables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CorrectOptionTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCorrectOptionTables(CorrectOptionTable correctOptionTable)
        {
            base.AddObject("CorrectOptionTables", correctOptionTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExamTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExamTables(ExamTable examTable)
        {
            base.AddObject("ExamTables", examTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OptionTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOptionTables(OptionTable optionTable)
        {
            base.AddObject("OptionTables", optionTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuestionTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuestionTables(QuestionTable questionTable)
        {
            base.AddObject("QuestionTables", questionTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ResultTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToResultTables(ResultTable resultTable)
        {
            base.AddObject("ResultTables", resultTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserTables(UserTable userTable)
        {
            base.AddObject("UserTables", userTable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Test", Name="CorrectOptionTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CorrectOptionTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CorrectOptionTable object.
        /// </summary>
        /// <param name="questionİD">Initial value of the QuestionİD property.</param>
        /// <param name="cavabDuzgun">Initial value of the CavabDuzgun property.</param>
        public static CorrectOptionTable CreateCorrectOptionTable(global::System.Int32 questionİD, global::System.String cavabDuzgun)
        {
            CorrectOptionTable correctOptionTable = new CorrectOptionTable();
            correctOptionTable.QuestionİD = questionİD;
            correctOptionTable.CavabDuzgun = cavabDuzgun;
            return correctOptionTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionİD
        {
            get
            {
                return _QuestionİD;
            }
            set
            {
                if (_QuestionİD != value)
                {
                    OnQuestionİDChanging(value);
                    ReportPropertyChanging("QuestionİD");
                    _QuestionİD = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("QuestionİD");
                    OnQuestionİDChanged();
                }
            }
        }
        private global::System.Int32 _QuestionİD;
        partial void OnQuestionİDChanging(global::System.Int32 value);
        partial void OnQuestionİDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CavabDuzgun
        {
            get
            {
                return _CavabDuzgun;
            }
            set
            {
                OnCavabDuzgunChanging(value);
                ReportPropertyChanging("CavabDuzgun");
                _CavabDuzgun = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CavabDuzgun");
                OnCavabDuzgunChanged();
            }
        }
        private global::System.String _CavabDuzgun;
        partial void OnCavabDuzgunChanging(global::System.String value);
        partial void OnCavabDuzgunChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_CorrectOptionTable_QuestionTable", "QuestionTable")]
        public QuestionTable QuestionTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionTable>("Test.FK_CorrectOptionTable_QuestionTable", "QuestionTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionTable>("Test.FK_CorrectOptionTable_QuestionTable", "QuestionTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuestionTable> QuestionTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionTable>("Test.FK_CorrectOptionTable_QuestionTable", "QuestionTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuestionTable>("Test.FK_CorrectOptionTable_QuestionTable", "QuestionTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Test", Name="ExamTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExamTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExamTable object.
        /// </summary>
        /// <param name="examID">Initial value of the ExamID property.</param>
        /// <param name="imtahanAd">Initial value of the ImtahanAd property.</param>
        public static ExamTable CreateExamTable(global::System.Int32 examID, global::System.String imtahanAd)
        {
            ExamTable examTable = new ExamTable();
            examTable.ExamID = examID;
            examTable.ImtahanAd = imtahanAd;
            return examTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamID
        {
            get
            {
                return _ExamID;
            }
            set
            {
                if (_ExamID != value)
                {
                    OnExamIDChanging(value);
                    ReportPropertyChanging("ExamID");
                    _ExamID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExamID");
                    OnExamIDChanged();
                }
            }
        }
        private global::System.Int32 _ExamID;
        partial void OnExamIDChanging(global::System.Int32 value);
        partial void OnExamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImtahanAd
        {
            get
            {
                return _ImtahanAd;
            }
            set
            {
                OnImtahanAdChanging(value);
                ReportPropertyChanging("ImtahanAd");
                _ImtahanAd = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImtahanAd");
                OnImtahanAdChanged();
            }
        }
        private global::System.String _ImtahanAd;
        partial void OnImtahanAdChanging(global::System.String value);
        partial void OnImtahanAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> YaradilmaTarixi
        {
            get
            {
                return _YaradilmaTarixi;
            }
            set
            {
                OnYaradilmaTarixiChanging(value);
                ReportPropertyChanging("YaradilmaTarixi");
                _YaradilmaTarixi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YaradilmaTarixi");
                OnYaradilmaTarixiChanged();
            }
        }
        private Nullable<global::System.DateTime> _YaradilmaTarixi;
        partial void OnYaradilmaTarixiChanging(Nullable<global::System.DateTime> value);
        partial void OnYaradilmaTarixiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_QuestionTable_ExamTable", "QuestionTable")]
        public EntityCollection<QuestionTable> QuestionTables
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<QuestionTable>("Test.FK_QuestionTable_ExamTable", "QuestionTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<QuestionTable>("Test.FK_QuestionTable_ExamTable", "QuestionTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_ResultTable_ExamTable", "ResultTable")]
        public EntityCollection<ResultTable> ResultTables
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ResultTable>("Test.FK_ResultTable_ExamTable", "ResultTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ResultTable>("Test.FK_ResultTable_ExamTable", "ResultTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Test", Name="OptionTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OptionTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OptionTable object.
        /// </summary>
        /// <param name="optionID">Initial value of the OptionID property.</param>
        /// <param name="questionID">Initial value of the QuestionID property.</param>
        /// <param name="variant">Initial value of the Variant property.</param>
        /// <param name="variantIsare">Initial value of the VariantIsare property.</param>
        public static OptionTable CreateOptionTable(global::System.Int32 optionID, global::System.Int32 questionID, global::System.String variant, global::System.String variantIsare)
        {
            OptionTable optionTable = new OptionTable();
            optionTable.OptionID = optionID;
            optionTable.QuestionID = questionID;
            optionTable.Variant = variant;
            optionTable.VariantIsare = variantIsare;
            return optionTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OptionID
        {
            get
            {
                return _OptionID;
            }
            set
            {
                if (_OptionID != value)
                {
                    OnOptionIDChanging(value);
                    ReportPropertyChanging("OptionID");
                    _OptionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OptionID");
                    OnOptionIDChanged();
                }
            }
        }
        private global::System.Int32 _OptionID;
        partial void OnOptionIDChanging(global::System.Int32 value);
        partial void OnOptionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionID
        {
            get
            {
                return _QuestionID;
            }
            set
            {
                OnQuestionIDChanging(value);
                ReportPropertyChanging("QuestionID");
                _QuestionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QuestionID");
                OnQuestionIDChanged();
            }
        }
        private global::System.Int32 _QuestionID;
        partial void OnQuestionIDChanging(global::System.Int32 value);
        partial void OnQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Variant
        {
            get
            {
                return _Variant;
            }
            set
            {
                OnVariantChanging(value);
                ReportPropertyChanging("Variant");
                _Variant = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Variant");
                OnVariantChanged();
            }
        }
        private global::System.String _Variant;
        partial void OnVariantChanging(global::System.String value);
        partial void OnVariantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VariantIsare
        {
            get
            {
                return _VariantIsare;
            }
            set
            {
                OnVariantIsareChanging(value);
                ReportPropertyChanging("VariantIsare");
                _VariantIsare = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VariantIsare");
                OnVariantIsareChanged();
            }
        }
        private global::System.String _VariantIsare;
        partial void OnVariantIsareChanging(global::System.String value);
        partial void OnVariantIsareChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Sil
        {
            get
            {
                return _Sil;
            }
            set
            {
                OnSilChanging(value);
                ReportPropertyChanging("Sil");
                _Sil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sil");
                OnSilChanged();
            }
        }
        private Nullable<global::System.Boolean> _Sil;
        partial void OnSilChanging(Nullable<global::System.Boolean> value);
        partial void OnSilChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_OptionTable_QuestionTable", "QuestionTable")]
        public QuestionTable QuestionTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionTable>("Test.FK_OptionTable_QuestionTable", "QuestionTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionTable>("Test.FK_OptionTable_QuestionTable", "QuestionTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<QuestionTable> QuestionTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<QuestionTable>("Test.FK_OptionTable_QuestionTable", "QuestionTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<QuestionTable>("Test.FK_OptionTable_QuestionTable", "QuestionTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Test", Name="QuestionTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuestionTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuestionTable object.
        /// </summary>
        /// <param name="questionID">Initial value of the QuestionID property.</param>
        /// <param name="examID">Initial value of the ExamID property.</param>
        /// <param name="sual">Initial value of the Sual property.</param>
        public static QuestionTable CreateQuestionTable(global::System.Int32 questionID, global::System.Int32 examID, global::System.String sual)
        {
            QuestionTable questionTable = new QuestionTable();
            questionTable.QuestionID = questionID;
            questionTable.ExamID = examID;
            questionTable.Sual = sual;
            return questionTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionID
        {
            get
            {
                return _QuestionID;
            }
            set
            {
                if (_QuestionID != value)
                {
                    OnQuestionIDChanging(value);
                    ReportPropertyChanging("QuestionID");
                    _QuestionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("QuestionID");
                    OnQuestionIDChanged();
                }
            }
        }
        private global::System.Int32 _QuestionID;
        partial void OnQuestionIDChanging(global::System.Int32 value);
        partial void OnQuestionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamID
        {
            get
            {
                return _ExamID;
            }
            set
            {
                OnExamIDChanging(value);
                ReportPropertyChanging("ExamID");
                _ExamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExamID");
                OnExamIDChanged();
            }
        }
        private global::System.Int32 _ExamID;
        partial void OnExamIDChanging(global::System.Int32 value);
        partial void OnExamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sual
        {
            get
            {
                return _Sual;
            }
            set
            {
                OnSualChanging(value);
                ReportPropertyChanging("Sual");
                _Sual = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sual");
                OnSualChanged();
            }
        }
        private global::System.String _Sual;
        partial void OnSualChanging(global::System.String value);
        partial void OnSualChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_CorrectOptionTable_QuestionTable", "CorrectOptionTable")]
        public CorrectOptionTable CorrectOptionTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CorrectOptionTable>("Test.FK_CorrectOptionTable_QuestionTable", "CorrectOptionTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CorrectOptionTable>("Test.FK_CorrectOptionTable_QuestionTable", "CorrectOptionTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CorrectOptionTable> CorrectOptionTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CorrectOptionTable>("Test.FK_CorrectOptionTable_QuestionTable", "CorrectOptionTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CorrectOptionTable>("Test.FK_CorrectOptionTable_QuestionTable", "CorrectOptionTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_QuestionTable_ExamTable", "ExamTable")]
        public ExamTable ExamTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExamTable>("Test.FK_QuestionTable_ExamTable", "ExamTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExamTable>("Test.FK_QuestionTable_ExamTable", "ExamTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ExamTable> ExamTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExamTable>("Test.FK_QuestionTable_ExamTable", "ExamTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ExamTable>("Test.FK_QuestionTable_ExamTable", "ExamTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_OptionTable_QuestionTable", "OptionTable")]
        public EntityCollection<OptionTable> OptionTables
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OptionTable>("Test.FK_OptionTable_QuestionTable", "OptionTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OptionTable>("Test.FK_OptionTable_QuestionTable", "OptionTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Test", Name="ResultTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ResultTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ResultTable object.
        /// </summary>
        /// <param name="resultID">Initial value of the ResultID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="examID">Initial value of the ExamID property.</param>
        public static ResultTable CreateResultTable(global::System.Int32 resultID, global::System.Int32 userID, global::System.Int32 examID)
        {
            ResultTable resultTable = new ResultTable();
            resultTable.ResultID = resultID;
            resultTable.UserID = userID;
            resultTable.ExamID = examID;
            return resultTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResultID
        {
            get
            {
                return _ResultID;
            }
            set
            {
                if (_ResultID != value)
                {
                    OnResultIDChanging(value);
                    ReportPropertyChanging("ResultID");
                    _ResultID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResultID");
                    OnResultIDChanged();
                }
            }
        }
        private global::System.Int32 _ResultID;
        partial void OnResultIDChanging(global::System.Int32 value);
        partial void OnResultIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExamID
        {
            get
            {
                return _ExamID;
            }
            set
            {
                OnExamIDChanging(value);
                ReportPropertyChanging("ExamID");
                _ExamID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExamID");
                OnExamIDChanged();
            }
        }
        private global::System.Int32 _ExamID;
        partial void OnExamIDChanging(global::System.Int32 value);
        partial void OnExamIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DuzgunSay
        {
            get
            {
                return _DuzgunSay;
            }
            set
            {
                OnDuzgunSayChanging(value);
                ReportPropertyChanging("DuzgunSay");
                _DuzgunSay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DuzgunSay");
                OnDuzgunSayChanged();
            }
        }
        private Nullable<global::System.Int32> _DuzgunSay;
        partial void OnDuzgunSayChanging(Nullable<global::System.Int32> value);
        partial void OnDuzgunSayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sehvsay
        {
            get
            {
                return _Sehvsay;
            }
            set
            {
                OnSehvsayChanging(value);
                ReportPropertyChanging("Sehvsay");
                _Sehvsay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sehvsay");
                OnSehvsayChanged();
            }
        }
        private Nullable<global::System.Int32> _Sehvsay;
        partial void OnSehvsayChanging(Nullable<global::System.Int32> value);
        partial void OnSehvsayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Faiz
        {
            get
            {
                return _Faiz;
            }
            set
            {
                OnFaizChanging(value);
                ReportPropertyChanging("Faiz");
                _Faiz = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Faiz");
                OnFaizChanged();
            }
        }
        private Nullable<global::System.Int32> _Faiz;
        partial void OnFaizChanging(Nullable<global::System.Int32> value);
        partial void OnFaizChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ImtahanTarixi
        {
            get
            {
                return _ImtahanTarixi;
            }
            set
            {
                OnImtahanTarixiChanging(value);
                ReportPropertyChanging("ImtahanTarixi");
                _ImtahanTarixi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImtahanTarixi");
                OnImtahanTarixiChanged();
            }
        }
        private Nullable<global::System.DateTime> _ImtahanTarixi;
        partial void OnImtahanTarixiChanging(Nullable<global::System.DateTime> value);
        partial void OnImtahanTarixiChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_ResultTable_ExamTable", "ExamTable")]
        public ExamTable ExamTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExamTable>("Test.FK_ResultTable_ExamTable", "ExamTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExamTable>("Test.FK_ResultTable_ExamTable", "ExamTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ExamTable> ExamTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ExamTable>("Test.FK_ResultTable_ExamTable", "ExamTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ExamTable>("Test.FK_ResultTable_ExamTable", "ExamTable", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_ResultTable_UserTable", "UserTable")]
        public UserTable UserTable
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserTable>("Test.FK_ResultTable_UserTable", "UserTable").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserTable>("Test.FK_ResultTable_UserTable", "UserTable").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserTable> UserTableReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserTable>("Test.FK_ResultTable_UserTable", "UserTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserTable>("Test.FK_ResultTable_UserTable", "UserTable", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Test", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Test", Name="UserTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserTable object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="ad">Initial value of the Ad property.</param>
        /// <param name="soyad">Initial value of the Soyad property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="yas">Initial value of the Yas property.</param>
        /// <param name="sifre">Initial value of the Sifre property.</param>
        public static UserTable CreateUserTable(global::System.Int32 userID, global::System.String ad, global::System.String soyad, global::System.String email, global::System.Int32 yas, global::System.String sifre)
        {
            UserTable userTable = new UserTable();
            userTable.UserID = userID;
            userTable.Ad = ad;
            userTable.Soyad = soyad;
            userTable.Email = email;
            userTable.Yas = yas;
            userTable.Sifre = sifre;
            return userTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ad
        {
            get
            {
                return _Ad;
            }
            set
            {
                OnAdChanging(value);
                ReportPropertyChanging("Ad");
                _Ad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ad");
                OnAdChanged();
            }
        }
        private global::System.String _Ad;
        partial void OnAdChanging(global::System.String value);
        partial void OnAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Soyad
        {
            get
            {
                return _Soyad;
            }
            set
            {
                OnSoyadChanging(value);
                ReportPropertyChanging("Soyad");
                _Soyad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Soyad");
                OnSoyadChanged();
            }
        }
        private global::System.String _Soyad;
        partial void OnSoyadChanging(global::System.String value);
        partial void OnSoyadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adres
        {
            get
            {
                return _Adres;
            }
            set
            {
                OnAdresChanging(value);
                ReportPropertyChanging("Adres");
                _Adres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adres");
                OnAdresChanged();
            }
        }
        private global::System.String _Adres;
        partial void OnAdresChanging(global::System.String value);
        partial void OnAdresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Yas
        {
            get
            {
                return _Yas;
            }
            set
            {
                OnYasChanging(value);
                ReportPropertyChanging("Yas");
                _Yas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Yas");
                OnYasChanged();
            }
        }
        private global::System.Int32 _Yas;
        partial void OnYasChanging(global::System.Int32 value);
        partial void OnYasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sinif
        {
            get
            {
                return _Sinif;
            }
            set
            {
                OnSinifChanging(value);
                ReportPropertyChanging("Sinif");
                _Sinif = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sinif");
                OnSinifChanged();
            }
        }
        private global::System.String _Sinif;
        partial void OnSinifChanging(global::System.String value);
        partial void OnSinifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Qrup
        {
            get
            {
                return _Qrup;
            }
            set
            {
                OnQrupChanging(value);
                ReportPropertyChanging("Qrup");
                _Qrup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Qrup");
                OnQrupChanged();
            }
        }
        private global::System.String _Qrup;
        partial void OnQrupChanging(global::System.String value);
        partial void OnQrupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sifre
        {
            get
            {
                return _Sifre;
            }
            set
            {
                OnSifreChanging(value);
                ReportPropertyChanging("Sifre");
                _Sifre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Sifre");
                OnSifreChanged();
            }
        }
        private global::System.String _Sifre;
        partial void OnSifreChanging(global::System.String value);
        partial void OnSifreChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Test", "FK_ResultTable_UserTable", "ResultTable")]
        public EntityCollection<ResultTable> ResultTables
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ResultTable>("Test.FK_ResultTable_UserTable", "ResultTable");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ResultTable>("Test.FK_ResultTable_UserTable", "ResultTable", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
